### ISSUE TITLE
image_caption训练过程中报错

### ISSUE THREAD

**Issue by 1115712590** [chenxie95/deeplearning_course_sjtu#10]
按照requirements.txt配好了环境，且按照README所说，将需要的包拷贝到了对应位置，但训练在第一个epoch进行一半时报错。请问是需要安装java吗？

Traceback (most recent call last):                                                                                                                                     
  File "main.py", line 352, in <module>
    fire.Fire(Runner)
  File "/home/guoziao/anaconda3/envs/sed/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/guoziao/anaconda3/envs/sed/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/guoziao/anaconda3/envs/sed/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "main.py", line 347, in train_evaluate
    self.train(config_file, **kwargs)
  File "main.py", line 226, in train
    **config["sample_args"])[0]
  File "main.py", line 163, in evaluate_model
    key_to_refs = ptb_tokenize(key_to_refs)
  File "/mnt/nas/home/guoziao/ai_proj/image_caption/image_captioning/utils/util.py", line 25, in ptb_tokenize
    key_to_captions = tokenizer.tokenize(captions_for_image)
  File "/home/guoziao/anaconda3/envs/sed/lib/python3.7/site-packages/pycocoevalcap/tokenizer/ptbtokenizer.py", line 52, in tokenize
    stdout=subprocess.PIPE)
  File "/home/guoziao/anaconda3/envs/sed/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/guoziao/anaconda3/envs/sed/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'java': 'java'

**Comment by chenxie95** [comment]
这个是针对哪个题目呢？如果是语言模型，VAE和语音识别，是不需要JAVA的

**Comment by 1115712590** [comment]
是图片摘要生成项目

**Comment by wsntxxn** [comment]
是的，要load java：

**Comment by 1115712590** [comment]
谢谢老师助教！
