### ISSUE TITLE
Can't pickle local object 'sequential_collate.<locals>.wrapper

### ISSUE THREAD

**Issue by zzl120** [chenxie95/deeplearning_course_sjtu#12]
在跑sound event detection时遇到了这个问题，我是在本地运行的代码
raceback (most recent call last):
                                                                                                                         File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "D:\sound_event_detection\run.py", line 329, in <module>
  File "D:\APP\Python\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
        fire.Fire(Runner)exitcode = _main(fd, parent_sentinel)

  File "D:\APP\Python\Python39\lib\site-packages\fire\core.py", line 141, in Fire
  File "D:\APP\Python\Python39\lib\multiprocessing\spawn.py", line 126, in _main
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
      File "D:\APP\Python\Python39\lib\site-packages\fire\core.py", line 466, in _Fire
self = reduction.pickle.load(from_parent)
component, remaining_args = _CallAndUpdateTrace(EOFError
: Ran out of input  File "D:\APP\Python\Python39\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace

    component = fn(*varargs, **kwargs)
  File "D:\sound_event_detection\run.py", line 324, in train_evaluate
    experiment_path = self.train(config_file)
  File "D:\sound_event_detection\run.py", line 132, in train
    for batch in trainloader:
  File "D:\APP\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "D:\APP\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\APP\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "D:\APP\Python\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\APP\Python\Python39\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\APP\Python\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\APP\Python\Python39\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\APP\Python\Python39\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'sequential_collate.<locals>.wrapper'

**Comment by wsntxxn** [comment]
有改代码吗

**Comment by wsntxxn** [comment]
是windows多进程的问题，windows多进程和unix实现有所不同，可以把collate_fn改成类装饰器，或者最好能在linux上跑

**Comment by zzl120** [comment]
换成在linux上跑了，没问题了，谢谢。
