### ISSUE TITLE
image captioning的demo运行报错

### ISSUE THREAD

**Issue by BravoFr0st** [chenxie95/deeplearning_course_sjtu#13]

**Comment by BravoFr0st** [comment]
Traceback (most recent call last):
  File "/dssg/home/acct-stu/stu469/3611Proj/image_captioning/main.py", line 347, in <module>
    fire.Fire(Runner)
  File "/dssg/home/acct-stu/stu469/.conda/envs/pytorch-icc/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/dssg/home/acct-stu/stu469/.conda/envs/pytorch-icc/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/dssg/home/acct-stu/stu469/.conda/envs/pytorch-icc/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/dssg/home/acct-stu/stu469/3611Proj/image_captioning/main.py", line 342, in train_evaluate
    self.train(config_file, **kwargs)
  File "/dssg/home/acct-stu/stu469/3611Proj/image_captioning/main.py", line 173, in train
    dataloaders = self.get_dataloaders(args)
  File "/dssg/home/acct-stu/stu469/3611Proj/image_captioning/main.py", line 45, in get_dataloaders
    train_set = Flickr8kDataset(
  File "/dssg/home/acct-stu/stu469/3611Proj/image_captioning/dataset.py", line 61, in __init__
    self.vocab, self.word2idx, self.idx2word, self.max_len = self.__construct_vocab()
  File "/dssg/home/acct-stu/stu469/3611Proj/image_captioning/dataset.py", line 96, in __construct_vocab
    cap_words = nltk.word_tokenize(cap.lower())
  File "/dssg/home/acct-stu/stu469/.conda/envs/pytorch-icc/lib/python3.9/site-packages/nltk/tokenize/__init__.py", line 129, in word_tokenize
    sentences = [text] if preserve_line else sent_tokenize(text, language)
  File "/dssg/home/acct-stu/stu469/.conda/envs/pytorch-icc/lib/python3.9/site-packages/nltk/tokenize/__init__.py", line 106, in sent_tokenize
    tokenizer = load(f"tokenizers/punkt/{language}.pickle")
  File "/dssg/home/acct-stu/stu469/.conda/envs/pytorch-icc/lib/python3.9/site-packages/nltk/data.py", line 750, in load
    opened_resource = _open(resource_url)
  File "/dssg/home/acct-stu/stu469/.conda/envs/pytorch-icc/lib/python3.9/site-packages/nltk/data.py", line 876, in _open
    return find(path_, path + [""]).open()
  File "/dssg/home/acct-stu/stu469/.conda/envs/pytorch-icc/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93mpunkt[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt/PY3/english.pickle[0m

  Searched in:
    - '/dssg/home/acct-stu/stu469/nltk_data'
    - '/dssg/home/acct-stu/stu469/.conda/envs/pytorch-icc/nltk_data'
    - '/dssg/home/acct-stu/stu469/.conda/envs/pytorch-icc/share/nltk_data'
    - '/dssg/home/acct-stu/stu469/.conda/envs/pytorch-icc/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************

**Comment by wsntxxn** [comment]
按照提示下载资源：
`import nltk;
nltk.download('punkt')
`

**Comment by BravoFr0st** [comment]
在nltk数据集和resnet101-63fe2227.pth都正确下载之后, Slurm系统提示oom, 这个demo大概需要申请多少RAM才能通过

**Comment by cantabile-kwok** [comment]
建议是conf里面load to memory改成false

**Comment by wsntxxn** [comment]
memory 的需求我也忘了，方便的做法就是如同学所说，把配置文件里load_img_to_memory改成False
